apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgressql
spec:
  selector:
    matchLabels:
      app: postgressql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgressql
    spec:
      containers:
      - name: postgressql
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "pg#123"
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_DB
          value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgressql-service
spec:
  selector:
    app: postgressql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: marciogabriel1998/aula-kube-news:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "pg#123"
        - name: DB_HOST
          value: "postgressql-service"
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

